import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule, FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { UserRole, UserStatus } from '../../core/models/api.models';
import { ErrorService } from '../../core/services/error.service';
import { UsersService } from '../../core/services/users.service';
import { ToastComponent } from '../../shared/ui/toast.component';
import { isUuid } from '../../shared/validation/validators';

@Component({
  selector: 'app-users', standalone: true, imports: [FormsModule, ReactiveFormsModule, ToastComponent], changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<section class="page-heading"><div><p class="eyebrow">ADMINISTRAÇÃO</p><h1>Usuários</h1><p class="page-subtitle">Crie e consulte acessos da operação.</p></div></section>@if (message()) { <app-toast [message]="message()" [error]="isError()" /> }<div class="users-layout"><section class="panel form-panel"><div class="panel-title"><div><h2>Novo usuário</h2><p>O usuário poderá entrar imediatamente.</p></div></div><form [formGroup]="form" (ngSubmit)="create()" novalidate><label for="username">Nome</label><input id="username" formControlName="username" placeholder="Nome completo"><label for="email">E-mail</label><input id="email" type="email" formControlName="email" placeholder="voce@empresa.com"><label for="phone">Telefone</label><input id="phone" formControlName="phone" placeholder="+5511999999999"><label for="password">Senha</label><input id="password" type="password" formControlName="password" placeholder="Mínimo de 8 caracteres"><label for="role">Perfil</label><select id="role" formControlName="role"><option [ngValue]="UserRole.Customer">Cliente</option><option [ngValue]="UserRole.Manager">Gerente</option><option [ngValue]="UserRole.Admin">Administrador</option></select><button class="button button-primary button-full" type="submit" [disabled]="loading()">{{ loading() ? 'Criando...' : 'Criar usuário' }}</button></form></section><section class="panel user-lookup"><div class="panel-title"><div><h2>Consultar usuário</h2><p>Use o UUID para consultar ou excluir.</p></div></div><form class="lookup-form" (ngSubmit)="lookup()"><input [(ngModel)]="lookupId" name="lookupId" placeholder="UUID do usuário"><button class="button button-ghost" type="submit">Consultar</button></form>@if (user(); as current) {<div class="user-result"><span class="avatar avatar-large">{{ current.name.slice(0, 2).toUpperCase() }}</span><div><h3>{{ current.name }}</h3><p>{{ current.email }}</p><small>{{ roleName(current.role) }} · {{ statusName(current.status) }}</small></div><button class="danger-link" type="button" (click)="remove(current.id)">Excluir</button></div>}</section></div>`
})
export class UsersComponent {
  readonly UserRole = UserRole; private readonly fb = inject(FormBuilder); private readonly service = inject(UsersService); private readonly errors = inject(ErrorService);
  readonly loading = signal(false); readonly message = signal(''); readonly isError = signal(false); readonly user = signal<import('../../core/models/api.models').User | null>(null); lookupId = '';
   readonly form = this.fb.nonNullable.group({ username: ['', [Validators.required, Validators.minLength(3), Validators.maxLength(50)]], email: ['', [Validators.required, Validators.email, Validators.maxLength(100)]], phone: ['', [Validators.required, Validators.pattern(/^\+[1-9]\d{1,14}$/)]], password: ['', [Validators.required, Validators.minLength(8), Validators.pattern(/^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[!?*.@#$%^&+=]).+$/)]], role: [UserRole.Customer] });
  create(): void { this.message.set(''); this.isError.set(false); if (this.form.invalid) { this.form.markAllAsTouched(); return; } this.loading.set(true); const value = this.form.getRawValue(); this.service.create({ ...value, status: UserStatus.Active }).subscribe({ next: ({ data }) => { this.loading.set(false); this.user.set(data); this.message.set('Usuário criado com sucesso.'); this.form.reset({ role: UserRole.Customer }); }, error: error => { this.loading.set(false); this.isError.set(true); this.message.set(this.errors.message(error, 'Não foi possível criar o usuário.')); } }); }
   lookup(): void { this.message.set(''); if (!isUuid(this.lookupId)) { this.isError.set(true); this.message.set('Informe um UUID válido.'); return; } this.service.get(this.lookupId.trim()).subscribe({ next: ({ data }) => { this.user.set(data); }, error: error => { this.isError.set(true); this.message.set(this.errors.message(error, 'Usuário não encontrado.')); } }); }
  remove(id: string): void { if (!confirm('Excluir este usuário?')) return; this.service.delete(id).subscribe({ next: () => { this.user.set(null); this.message.set('Usuário excluído.'); this.isError.set(false); }, error: error => { this.isError.set(true); this.message.set(this.errors.message(error, 'Não foi possível excluir o usuário.')); } }); }
  roleName(role: UserRole): string { return ['Nenhum', 'Cliente', 'Gerente', 'Administrador'][role] ?? 'Desconhecido'; }
  statusName(status: UserStatus): string { return ['Desconhecido', 'Ativo', 'Inativo', 'Suspenso'][status] ?? 'Desconhecido'; }
}
